### ISSUE TITLE
Join to Crystal Tools organization

### ISSUE THREAD

**Issue by faustinoaq** [juanedi/crystal-spacemacs-layer#1]
Hola @juanedi some Crystal community members have the idea of a [Crystal Tools organization](https://github.com/crystal-lang-tools) inspired by [Julia Editor Support organization](https://github.com/JuliaEditorSupport).

We are adding repositories for sublime, emacs, vim, vscode, atom, etc. All in one place well documented easy to follow, collaborate and maintain. :-)

If you accept the proposal of move your repo to [Crystal Tools organization](https://github.com/crystal-lang-tools), leave a message in [Gitter room](https://gitter.im/crystal-scry/Lobby?source=orgpage) first.

Gracias por tu aporte a la comunidad de Crystal. 💓

**Comment by faustinoaq** [comment]
@juanedi https://github.com/crystal-lang-tools is awaiting for you :smile: 

![screenshot_20170824_124638](https://user-images.githubusercontent.com/3067335/29680477-47c94900-88ca-11e7-9b2c-02311c6b72da.png)

**Comment by juanedi** [comment]
Hello @faustinoaq! Please excuse me for the delay.
This sounds like a nice idea! Congrats and thank you for organizing this.

My only doubt would be if it really makes sense to add the spacemacs layer there. I feel like maybe that should be the place for a crystal-mode package. This layer is nothing more than a thin wrapper around the best emacs mode package I found (well, to be fair, it has that super cool auto formatting thing :-P)

My impression is that, ideally, we would have:
- a crystal-mode emacs package hosted in `crystal-tools`
- an official spacemacs layer merged into the spacemacs repo.

So, I have no problem in sharing this project's ownership, I just want to make sure it's the right way to proceed :-)

**Comment by faustinoaq** [comment]
Well, `crystal-mode` is [awaiting too](https://github.com/dotmilk/emacs-crystal-mode/issues/18) :sweat_smile: WDYT @keplersj?

**Comment by keplersj** [comment]
I agree with the points @juanedi bring up. This repo would probably best being upstreamed into spacemacs - [looks like it's about time to have a Crystal layer](https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Blang). The `crystal-lang-tools` org would be best keeping to regular emacs packages (grammar, spec runner, language server, etc.), and allow spacemacs to keep ownership of its Crystal configuration.

This all being said this are my observations after looking at emacs and spacemacs very briefly. This decisions should be backed up by people who actually use emacs and spacemacs before we move forward.

As well @faustinoaq it's worth noting that you've invited @dotmilk to `crystal-lang-tools`, however this layer refers to @ggiraldez's emacs package which is forked from @dotmilk's. Looking at how many emacs packages and forks there are for Crystal I think crystal-lang-tools could help play a role in unifying them.

**Comment by faustinoaq** [comment]
@keplersj I agree. I was confused about emacs world. So, let me close this issue.

We can discuss on [Gitter](https://gitter.im/crystal-scry/Lobby) about unify (or create a new) emacs repo.
